### ISSUE TITLE
Project Metadata Creation Page

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#131]
The metadata page for projects needs to come to life. It is this one: http://bbc6.sics.se:8080/aegis/#!/project/1045/extended-metadata
The projects metadata corresponds to catalogues in DCAT-AP. The fields should be based on these specifications. The following fields should be available (for now):
- title
- description
- publisher (an foaf:Agent)
- homepage
- language
- licence
- spatial

The fields modified and issued will be set automatically. 
The users input should generate a RDF string, which will be send to the backend. It's a good idea to use an existing JavaScript library for that (https://www.w3.org/community/rdfjs/wiki/Comparison_of_RDFJS_libraries). As serialisation format JSON-LD is maybe the best fit here. An similar example can be found here: https://www.europeandataportal.eu/data/api/catalogues/edp

**Comment by FabiApfelkern** [comment]
First results here: https://github.com/aegisbigdata/hopsworks/tree/feature/project-metadata-creation-page

**Comment by FabiApfelkern** [comment]
@aldafu @Kritzzz Thanks. I have some questions: 
- You did the metadata for the datasets and not for the project here? 
- Was there an issue with installing jsonld via bower?

**Comment by Kritzzz** [comment]
- Ah, initially I just extended the existing view for "ExtendedMetadata" - didn't realize that projects and datasets do not share the same template. I'll fix that.
- Yes, when installing jsonld via bower seemingly an outdated / incomplete version of jsonld is downloaded to the bower_components directory. When including the bower version, there is no compiled .js file / dist folder, just the source code of the library which the browser can't interpret (e.g. because of numerous require('...') -statements in the source code). That's why I added jsonld via npm.

**Comment by FabiApfelkern** [comment]
Thanks!
We discussed this issue in our telco today and there seems to alrady a solution for this kind of problem. You can use npm packages with bower. It was for example done with the apexcharts library, see
https://github.com/aegisbigdata/hopsworks/blob/dev/aegis-web/yo/bower.json

Can you check this out?

**Comment by Kritzzz** [comment]
okay - json-ld is now loaded via the bower-npm-resolver instead of npm directly!

**Comment by aldafu** [comment]
Added a branch with further improvements here:
https://github.com/aegisbigdata/hopsworks/tree/feature/project-metadata-creation-page-alex

See commit messages for details.
