### ISSUE TITLE
Create a new more integrated frontend

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#15]
Angular 1 is outdated and we have to work around a lot for a smooth user experience. May be a good a approach is to somehow start from scratch....

**Comment by jimdowling** [comment]
As a pretty experienced developer (at this stage), I would strongly 
recommend against this.

You really don't know how much work this is, until you've done it before.

Netscape rewriting their software in 1995 (took them 3 years) is the 
standard business case they use in mgmt school.

More reading here:

http://www.onstartups.com/tabid/3339/bid/2596/Why-You-Should-Almost-Never-Rewrite-Your-Software.aspx


On the other hand, there is no problem redoing .css or using 
angular-material instead of bootstrap in places.

The main disadvantage of Angular-1 is that it doesn't scale. But we 
wrote our SPA to scale - we don't use scope variables, except in a few 
judicious places. Instead we use 'self' variables, and refresh UI 
elements when functions return (e.g., when you create a new project, we 
refresh the list of projects in code (just like React), instead of 
relying on a 2-way scope variable to refresh the list. This idiom allows 
us to build a scalable SPA.).

My 2 cents

Jim

**Comment by cbotsikas** [comment]
Not to be done
