### ISSUE TITLE
Add the earthquake risk map into the base visualizer

### ISSUE THREAD

**Issue by pitsios-s** [aegisbigdata/documentation#158]

**Comment by pitsios-s** [comment]
Adding the earthquake risk map into the base visualizer is really easy (just copying the related code into the general notebook), so I don't have any problem proceeding with this issue.

The reason that I created a separated notebook is that this kind of map is highly related to a very specific case for the needs of the HDI demonstrator, while the base visualizer offers support for general case charts that can be used by everyone.

IMHO, keeping the two versions apart helps us showcase the benefit of extensibility of the tools provided by the AEGIS platform, in the sense that we offer a set of general tools (AEC, QB, Visualizer) for everyone, which can be easily extended (since they are just notebooks) by a data scientist to suit very specific needs.

But again, like I said I don't mind adding this support into the base visualizer if you believe that this is better.

What is your opinion on this @YuriGlickman , @FabiApfelkern , @kperakis

**Comment by kperakis** [comment]
I believe that separating the two versions adds value to the visualizer because as you mention we showcase that we have an extensible tool that can be used by external / 3rd party stakeholders in order to develop custom solutions (and perhaps offerings). I am not in favor of integrating the earthquake risk map into the base visualizer no matter how simple it might be.
