### ISSUE TITLE
Cleanup the Landing Page

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#3]
The content of the landing page is not clear and it is not well structured. Please adress the following issues:

* If the tabs (Popular Assets etc.) have no meaning remove them
* It is not clear what datasets are shown here
* Can the inline scroling be avoided?
* Number of datasets per page should be an intervall e.g. 10, 20, 30

![grafik](https://user-images.githubusercontent.com/1488424/43515977-544e66ac-9584-11e8-91bd-2841cf56b661.png)

**Comment by mmeglio** [comment]
•	If the tabs (Popular Assets etc.) have no meaning remove them **OK we’ll disable the tabs**
•	It is not clear what datasets are shown here **Currently the datasets showed come from some test queries...**
•	Can the inline scrolling be avoided? **Without the scrolling, how could we handle the display of many assets?**
•	Number of datasets per page should be an interval e.g. 10, 20, 30 **OK TO BE FIXED**

**Comment by YuriGlickman** [comment]
>>• Can the inline scrolling be avoided? Without the scrolling, how could we handle the display of many assets?
I am not an expert, but I see 2 obvious options:
You simply don't restrict the page length and provide the scrolling for the whole page instead of inline scrolling. Alternatively, you can dinamically calculate the number of the assets on one page basef on the window size, but it is a bit more difficult...
Both options are more user friendly...

**Comment by mmeglio** [comment]
We'll remove the inline scroll.
