### ISSUE TITLE
Local Development Frontend Tutorial

### ISSUE THREAD

**Issue by FabiApfelkern** [aegisbigdata/documentation#66]

**Comment by FabiApfelkern** [comment]
Our initial concept is not working anymore. We will investifate further.

**Comment by FabiApfelkern** [comment]
Will come this week....

**Comment by FabiApfelkern** [comment]
A first test:

* Install serveStatic module: npm install serve-static --save-dev
 * Add the following line Gruntfile.js at top: var serveStatic = require('serve-static');
 * Replace all occurrences of connect.static with serveStatic
* In /app/scripts/js/util.js: getLocationBase() and getApiLocationBase() Replace location.protocol + "//" + location.hostname +":" + getPort() with 'http://bbc6.sics.se:8080'
 * Use grunt serve to run web server
 * Disable CORS in web browser

**Comment by FabiApfelkern** [comment]
@cbotsikas Can you try this before we make more formal description?

**Comment by cbotsikas** [comment]
@FabiApfelkern yes, i'll check it.

**Comment by FabiApfelkern** [comment]
Thanks  @cbotsikas. Yes, I also don't like to change the code. But does your solution also change the code? 
@michaelalemu Can you check this?

**Comment by cbotsikas** [comment]
Yes i do modify the Gruntfile.js and the package.json files but those, i guess, are acceptable changes that we can afford to do permanently on the repo. I'm not changing any application source file. 
We could have a separate repo with all the necessary code to run and develop locally. I can investigate further if for some reason we shouldn't apply my modification in this repo.

**Comment by michaelalemu** [comment]
> Thanks @cbotsikas. Yes, I also don't like to change the code. But does your solution also change the code?
> @michaelalemu Can you check this?

I've checked it and @cbotsikas solution seems to be working fine.

**Comment by cbotsikas** [comment]
I've changed the latest frontend module in order to support our local development method, without the need of changing any files.

Please note that the latest code is under the [aegis-0.6](https://github.com/aegisbigdata/hopsworks/tree/aegis-0.6) branch and the working directory is [aegis-web/yo](https://github.com/aegisbigdata/hopsworks/tree/aegis-0.6/aegis-web/yo).
Install all requirements executing:
```
npm install
bowser install
```
and run your local UI using the `grunt serve` command

This should open your browser at http://localhost:9001 using our live server at http://bbc6.sics.se:8080

Also note that, all requests are proxied via localhost so that from your browser you shouldn't see any requests to bbc6.sics.se:8080.

**Comment by FabiApfelkern** [comment]
I guess we can close this?

**Comment by cbotsikas** [comment]
Yes, this was forgotten open..
